version: '3.3'
services:
  main_server:
    container_name: nestjs_api_main
    image: nestjs-api-dev
    environment:
      - DB_HOST=mongodb://mongodb/nest
      - LOG_HOST=nestjs_api_log
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - nesjs-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  log_server:
    container_name: nestjs_api_log
    image: nestjs-api-log
    environment:
      - DB_HOST=mongodb://mongodb/nest
      - LOG_HOST=nestjs_api_log
    build:
      context: .
      dockerfile: ./DockerfileLog
    ports:
      - 3001:3001
    networks:
      - nesjs-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    networks:
      - nesjs-network
    restart: always
networks:
  nesjs-network:
    driver: bridge
